### PR TITLE
added some simple lables to contact form

### LINKED ISSUE #85: Create Labels For Contact Form
**Is your feature request related to a problem? Please describe.**

When I first go to the contact form based on the placeholder text I understand what each input is for.  Once I start typing in the input field we don't have labels.  This can be confusing for the user.

**Describe the solution you'd like**

Add labels that would also help with accessibility.
- Name
- Email
- Enter your question here

### PR DESCRIPTION
**Pull request by Tye-Hadfield**
Fixes #85  

Changes proposed in this pull request:
- Added labels to contact form with using already had classes (Let me know if not what was required or I can help elsewhere on this issue)

Form

### CODE REVIEW

**Comment by ticet11** [comment]
It seems good, in that it does have the labels visible while a user is filling out the form. I'm not sure how heavily the accessibility is the goal on this specific issue. It may be worth the time to go through [this article](https://www.w3.org/WAI/tutorials/forms/) about accessibility in forms. I perused through, but didn't look very closely. One of the things that is mentioned is that nesting inputs inside of labels is good in that it implicitly associates the two tags, which may be necessary when you can't know an id coming from an API or some other situation, but it is sometimes not handled well by assistive technologies. 

Also, as a general tip, if you put the # symbol before the issue number, it will actually connect the two. For example: Fixes #85. And you can do this directly in commit messages, as well as pull requests.

**Comment by Tye-Hadfield** [comment]
Thanks ticet11 for the article and the tip on linking the issue to the PR! I was just using the React docs on how they specified how to use the label tag, though it didn't provide how screenwriters or accessibility tool would handle it.

**Review by gleekzorp — CHANGES_REQUESTED** [review]
Awesome job!  I appreciate you helping out.  I would agree with some of the topics that @ticet11 talked about in his comments above.

Let's make sure we follow accessibility standards.  Please go ahead and break the `<label>` tags out and add the `htmlFor` attribute to the labels with corresponding `id` on the `input` field for that `htmlFor`.  Please see a quick example [here](https://reactjs.org/docs/accessibility.html#labeling)

I also think we should style the labels to be on the left instead of the center.

I'm a little worried about the `package-lock.json` files being updated.  The one `package-lock.json` that lives in the root can just be deleted I think you accidentally created that one.  What are your thoughts on this @ticet11

**Comment by ticet11** [comment]
@gleekzorp It looks to me like he may have formatted it with a slightly different configuration than was previously used, because it marked the whole file as changed, but it looks like both sides are the same.

**Comment by Tye-Hadfield** [comment]
Hey Guys!

All I did was run the npm install and add no extra dependencies, I am happy to start this whole PR over and try again with the accessibility features?

**Comment by Tye-Hadfield** [comment]
Closing, please see new PR. 

https://github.com/code-experiment/code-experiment-website/pull/88

**Pull request closed without merging**
