### PR TITLE
Add labels to contact form 2.0

### PR DESCRIPTION
**Pull request by Tye-Hadfield**
Fixes issue #85  

Changes proposed in this pull request:
- Added the lables up to par with the accessibilty standards per React documentation provided by gleekzorp.
- Added a SCSS class for lables (Added a little margin to help with style)
-
contact-form

### CODE REVIEW

**Review by gleekzorp — CHANGES_REQUESTED** [review]
Thank you for the help!  I like the `text-align: start`, I always used `text-align: left`.  Please use `rem` or `em` for our sizes on the margin to keep with the rest of the codebase.  After that change we should be good.

**Comment by Tye-Hadfield** [comment]
All done my friend, thank you for allowing me to work with your team. :)

**Review by gleekzorp — CHANGES_REQUESTED** [review]
Thank you for updating the styles to use `em`.  Unfortunately, this pull request will have a merge conflict with our lasted merge request #83.  In that merge we updated `react-hook-forms` which caused us to do some modifications to our forms.  I will need you to resolve that conflict before I can merge this in.

The issue is going to be with the `contactForm`.

**Comment by Tye-Hadfield** [comment]
Hey gleekzorp, 

I have fixed the merge conflicts with the changing of the forms, rather than having the label as a single line I took note that your inputs had the props on their own lines so I followed that style, please let me know if you prefer to have the lables as a single line.

**Review by gleekzorp — APPROVED** [review]
Awesome!  I went ahead and did a minor change to the formatting since I think you manually did the formatting instead of using the new prettier way.  That is okay seeming as this prettier formatting change happened kind of in conjunction to when you started this pull request.  I have updated the wiki with the information on this, you can read it at https://github.com/code-experiment/code-experiment-website/wiki/Outside-Contributions#setup

Thank you for all the help!

**Pull request merged**
